version: '2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7861:7861
    volumes:
      - .:/app
    environment:
      - MYSTICAI_API_KEY=